
name: homework_Nov18

on: workflow_dispatch

jobs:
    runs-on: ubuntu-latest
    
      steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
        run: |
          echo Done
          ls -la
